In [8]:
import pandas as pd
from sklearn import (svm, preprocessing)
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (recall_score, precision_score, accuracy_score, confusion_matrix,)
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [10]:
data_train = pd.read_csv("Accident_train.csv")
data_test = pd.read_csv("Accident_test.csv")
#data_train.head()
#data_test.head()
#data_train.info()
#data_test.info()
#data_train.var()

In [11]:
#data_train["Weekday_of_Collision"].value_counts()
#data_train["Policing_Area"].value_counts()
#data_test["Policing_Area"].value_counts()
#data_test["Collision_Severity"].value_counts()
#data_test["Weekday_of_Collision"].value_counts()
data_train["Ped_Crossing_HC"].value_counts()
#print(type(data_train))

1.0    8529
3.0      26
2.0      18
Name: Ped_Crossing_HC, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# lable encoder for data_train
le.fit(data_train['Weekday_of_Collision'])
data_train['Weekday_of_Collision'] = le.transform(data_train['Weekday_of_Collision'])
le.fit(data_train['Policing_Area'].astype(str))
data_train['Policing_Area'] = le.transform(data_train['Policing_Area'].astype(str))

In [13]:
# Converting Nan Values to mean/mode etc.,
#data_train.isna().any()
#data_train.mean()
#data_train.isna().any()
data_train = data_train.fillna(data_train.median())

In [14]:
# lable encoder for data_test
le.fit(data_test['Collision_Severity'])
data_test['Collision_Severity'] = le.transform(data_test['Collision_Severity'])
le.fit(data_test['Weekday_of_Collision'])
data_test['Weekday_of_Collision'] = le.transform(data_test['Weekday_of_Collision'])
le.fit(data_test['Policing_Area'].astype(str))
data_test['Policing_Area'] = le.transform(data_test['Policing_Area'].astype(str))

In [15]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8849 entries, 0 to 8848
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Collision_Ref_No            8849 non-null   int64  
 1   Policing_Area               8849 non-null   int32  
 2   Collision_Severity          8849 non-null   int64  
 3   Weekday_of_Collision        8849 non-null   int32  
 4   Day_of_Collision            8849 non-null   int64  
 5   Month_of_Collision          8849 non-null   int64  
 6   Hour_of_Collision           8849 non-null   float64
 7   Carriageway_Type            8849 non-null   int64  
 8   Speed_Limit                 8849 non-null   int64  
 9   Junction_Detail             8849 non-null   float64
 10  Junction_Control            8849 non-null   float64
 11  Ped_Crossing_HC             8849 non-null   float64
 12  Ped_Crossing_PC             8849 non-null   float64
 13  Light_Conditions            8849 

In [16]:
# Converting Nan Values to mean/mode etc.,
#data_test.isna().any()
#data_test.mean()
data_test = data_test.fillna(data_test.median())

In [17]:
data_train.head()

Collision_Ref_No  Policing_Area  Collision_Severity  Weekday_of_Collision  \
0              3518             19                   3                     1   
1             10557              7                   3                     2   
2              5002             28                   3                     6   
3             11714              7                   3                     3   
4             12416             32                   3                     1   

   Day_of_Collision  Month_of_Collision  Hour_of_Collision  Carriageway_Type  \
0                 4                   8               14.0                13   
1                 8                   8               17.0                11   
2                 5                  11               17.0                 1   
3                18                  10               16.0                12   
4                23                  11                9.0                13   

   Speed_Limit  Junction_Detail  Junction_Control  Ped_Crossing_HC  \
0           60              1.0               1.0              1.0   
1           50             12.0               7.0              1.0   
2           60             12.0               7.0              1.0   
3           70              6.0               4.0              1.0   
4           60              6.0               7.0              1.0   

   Ped_Crossing_PC  Light_Conditions  Weather_Conditions  \
0              1.0                 2                   9   
1              1.0                 4                   3   
2              1.0                 2                   2   
3              1.0                 1                   3   
4              1.0                 2                   3   

   Road_Surface_Conditions  Special_Conditions_at_Site  
0                      9.0                         1.0  
1                      1.0                         1.0  
2                      2.0                         1.0  
3                      1.0                         1.0  
4                      1.0                         1.0

In [18]:
labels_train = data_train["Collision_Severity"]
data_train_x = data_train.drop(["Collision_Severity", "Collision_Ref_No"], axis=1)

data_test_x = data_test.drop(["Collision_Severity", "Collision_Ref_No"], axis=1)

In [19]:
data_train_x.shape

(8849, 15)

In [20]:
import collections
import numpy as np
from sklearn.decomposition import PCA

# splitting test vales into parts to find get lables
data_variables = train_test_split(data_train_x, labels_train, test_size = 0.25, random_state = 42)
#data_variables = train_test_split(data_train, labels_train, test_size=0.33, random_state=99)
data_train_l, data_test_l, labels_train_l, labels_test_l = data_variables

scaler = preprocessing.StandardScaler().fit(data_train_l)
train_data_scaled = scaler.transform(data_train_l)
test_data_scaled = scaler.transform(data_test_l)

test_data_scaled_x = scaler.transform(data_test_x)

#pca = PCA(n_components = 14)
#train_data_scaled = pca.fit_transform(data_train_l)
#test_data_scaled = pca.transform(data_test_l)
#explained_variance = pca.explained_variance_ratio_

#test_data_scaled_x = pca.transform(data_test_x)

In [21]:
classifier = RandomForestClassifier()
classifier.fit(train_data_scaled, labels_train_l)

classifier.fit(train_data_scaled, labels_train_l)

# Predicting test data with train data using classifier
predict_y = classifier.predict(test_data_scaled)

#print(type(predict_y))
a = np.array(predict_y)
print(collections.Counter(a))
#for x in predict_y:
#  print(x)

accuracy = classifier.score(test_data_scaled, labels_test_l)

precision = precision_score(labels_test_l, predict_y, average='micro')
recall = recall_score(labels_test_l, predict_y, average='micro')

cmatrix = confusion_matrix(labels_test_l, predict_y)
print("accuracy  : {}".format(accuracy))
print("accuracy[round]  : {}".format(round(accuracy, 3)))
print("precision : {}".format(precision))
print("recall    : {} \n".format(recall))
print("Confusion matrix \n{}\n\n".format(cmatrix))

Counter({3: 2183, 2: 30})
accuracy  : 0.8992318120198826
accuracy[round]  : 0.899
precision : 0.8992318120198826
recall    : 0.8992318120198826 

Confusion matrix 
[[   0    4   23]
 [   0   18  188]
 [   0    8 1972]]




In [22]:
#SVC
svc = SVC()
svc.fit(train_data_scaled, labels_train_l)
Y_pred = svc.predict(test_data_scaled)
a = np.array(Y_pred)
predict_svc = collections.Counter(a)
acc_svc = round(svc.score(test_data_scaled, labels_test_l) * 100, 2)
acc_svc

#KNN
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(train_data_scaled, labels_train_l)
Y_pred = knn.predict(test_data_scaled)
a = np.array(Y_pred)
predict_knn = collections.Counter(a)
acc_knn = round(knn.score(test_data_scaled, labels_test_l) * 100, 2)
acc_knn

# Logistic Regression
logreg = LogisticRegression()
logreg.fit(train_data_scaled, labels_train_l)
Y_pred = logreg.predict(test_data_scaled)
a = np.array(Y_pred)
predict_log = collections.Counter(a)
acc_log = round(logreg.score(test_data_scaled, labels_test_l) * 100, 2)
acc_log

# Gaussian Naive Bayes
gaussian = GaussianNB()
gaussian.fit(train_data_scaled, labels_train_l)
Y_pred = gaussian.predict(test_data_scaled)
a = np.array(Y_pred)
predict_gaussian = collections.Counter(a)
acc_gaussian = round(gaussian.score(test_data_scaled, labels_test_l) * 100, 2)
acc_gaussian

# Perceptron
perceptron = Perceptron()
perceptron.fit(train_data_scaled, labels_train_l)
Y_pred = perceptron.predict(test_data_scaled)
a = np.array(Y_pred)
predict_perceptron = collections.Counter(a)
acc_perceptron = round(perceptron.score(test_data_scaled, labels_test_l) * 100, 2)
acc_perceptron

# Linear SVC
linear_svc = LinearSVC()
linear_svc.fit(train_data_scaled, labels_train_l)
Y_pred = linear_svc.predict(test_data_scaled)
a = np.array(Y_pred)
predict_linear_svc = collections.Counter(a)
acc_linear_svc = round(linear_svc.score(test_data_scaled, labels_test_l) * 100, 2)
acc_linear_svc

# Stochastic Gradient Descent
sgd = SGDClassifier()
sgd.fit(train_data_scaled, labels_train_l)
Y_pred = sgd.predict(test_data_scaled)
a = np.array(Y_pred)
predict_sgd = collections.Counter(a)
acc_sgd = round(sgd.score(test_data_scaled, labels_test_l) * 100, 2)
acc_sgd

# Decision Tree
decision_tree = DecisionTreeClassifier()
decision_tree.fit(train_data_scaled, labels_train_l)
Y_pred = decision_tree.predict(test_data_scaled)
a = np.array(Y_pred)
predict_decision_tree = collections.Counter(a)
acc_decision_tree = round(decision_tree.score(test_data_scaled, labels_test_l) * 100, 2)
acc_decision_tree

# Random Forest
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(train_data_scaled, labels_train_l)
Y_pred = random_forest.predict(test_data_scaled)
a = np.array(Y_pred)
predict_random_forest = collections.Counter(a)
acc_random_forest = round(random_forest.score(test_data_scaled, labels_test_l) * 100, 2)
acc_random_forest

models = pd.DataFrame({
    'Model': ['Support Vector Machines', 'KNN', 'Logistic Regression', 
              'Random Forest', 'Naive Bayes', 'Perceptron', 
              'Stochastic Gradient Decent', 'Linear SVC', 
              'Decision Tree'],
    'Score': [acc_svc, acc_knn, acc_log, 
              acc_random_forest, acc_gaussian, acc_perceptron, 
              acc_sgd, acc_linear_svc, acc_decision_tree],
    'Count': [predict_svc, predict_knn, predict_log, 
              predict_random_forest, predict_gaussian, predict_perceptron, 
              predict_sgd, predict_linear_svc, predict_decision_tree]})
models.sort_values(by='Score', ascending=False)

C:\Users\saibhargav\anaconda3\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Model  Score                     Count
3               Random Forest  89.79          {3: 2185, 2: 28}
0     Support Vector Machines  89.47                 {3: 2213}
2         Logistic Regression  89.47                 {3: 2213}
6  Stochastic Gradient Decent  89.47                 {3: 2213}
7                  Linear SVC  89.47                 {3: 2213}
1                         KNN  86.99   {3: 2105, 2: 84, 1: 24}
8               Decision Tree  85.31  {3: 1958, 2: 215, 1: 40}
5                  Perceptron  83.01  {3: 1992, 2: 192, 1: 29}
4                 Naive Bayes   9.81  {1: 1982, 3: 193, 2: 38}